### ISSUE TITLE
Worker creates invalid container names

### ISSUE THREAD

**Issue by bjorhn** [PrefectHQ/prefect-azure#112]
Currently, using the worker to run deployments is broken unless the flow has a short and valid name. This is not a problem when running an old-fashioned agent.

prefect_azure/workers/container_instance.py doesn't do any sort of sanity checking when it comes to creating a container instance name, such as removing spaces or ensuring the name length is within Azure's limits. The invalid logic resides here: https://github.com/PrefectHQ/prefect-azure/blob/8f92ab76cb897eded99eeeed304517959a2caad6/prefect_azure/workers/container_instance.py#L552C46-L552C46

I think it would be better if the naming logic works exactly the same as in prefect_azure/container_instance.py, which lets the user set a name rather than hard-coding it based on the flow name, refrains from adding a prefect-prefix, pads 10 random characters instead of a guid and finally ensures that the name isn't too long for Azure (64 characters).

**Comment by desertaxle** [comment]
Thanks for the issue @bjorhn! The logic for ensuring that the created container names adhere to Azure's constraints was added to the `AzureContainerInstanceJob` block in https://github.com/PrefectHQ/prefect-azure/pull/92. It'll be straightforward to port over, so I'll mark this issue as a good first issue incase someone has the bandwidth to tackle this issue before I do.

**Comment by kbialka-eqr** [comment]
We're dragging our feet on moving over to workers because of this as well.

**Comment by bjorhn** [comment]
I don't have time to test this right now, but unless I'm missing something with the linked PR, the worker-based container instance will still use different logic for the naming of its container groups compared to the agent-based container instance.

The end result is that if anyone has logic that polls the container group names in some manner, they'll have to change things around depending on if the container groups are launched via agents or workers.

Essentially, the only part of the below description (from my original issue post) that's fixed is the two final parts about 10 random characters and the length check:

"I think it would be better if the naming logic works exactly the same as in prefect_azure/container_instance.py, which lets the user set a name rather than hard-coding it based on the flow name, refrains from adding a prefect-prefix, pads 10 random characters instead of a guid and finally ensures that the name isn't too long for Azure (64 characters)."

Unless it's too late, I could try to put together a PR for this over the holidays.

**Comment by tshapiro-eqr** [comment]
@desertaxle see this was merged to main, but its not present in tag v2.3.4 - from my end I don't care what the name is as long as its under 64 characters, so if @bjorhn wants to submit something after this is out to make it consistent with non-worker behavior it doesn't affect me at all.

**Comment by mdrobena** [comment]
Hi @desertaxle,

I am running into this very same issue, but with _Azure Container Instances - Push_ work pool in Prefect cloud. When the flow name length is too long I get back this error:

`Flow run could not be submitted to infrastructure: (InvalidDeployment) The provided deployment name 'prefect-send-notifications-joiners-leavers-57b21b3c-c7b3-485d-8bfa-aa9866da68bb' has a length of '79' which exceeds the maximum length of '64'. Please see https://aka.ms/arm-deploy for usage details.
Code: InvalidDeployment
Message: The provided deployment name 'prefect-send-notifications-joiners-leavers-57b21b3c-c7b3-485d-8bfa-aa9866da68bb' has a length of '79' which exceeds the maximum length of '64'. Please see https://aka.ms/arm-deploy for usage details.`

Should I create a separate issue from this one?

**Comment by jamesmarchant** [comment]
> Hi @desertaxle,
> 
> I am running into this very same issue, but with _Azure Container Instances - Push_ work pool in Prefect cloud. When the flow name length is too long I get back this error:
> 
> `Flow run could not be submitted to infrastructure: (InvalidDeployment) The provided deployment name 'prefect-send-notifications-joiners-leavers-57b21b3c-c7b3-485d-8bfa-aa9866da68bb' has a length of '79' which exceeds the maximum length of '64'. Please see https://aka.ms/arm-deploy for usage details. Code: InvalidDeployment Message: The provided deployment name 'prefect-send-notifications-joiners-leavers-57b21b3c-c7b3-485d-8bfa-aa9866da68bb' has a length of '79' which exceeds the maximum length of '64'. Please see https://aka.ms/arm-deploy for usage details.`
> 
> Should I create a separate issue from this one?

We are also experiencing this issue and it is preventing us from moving to the push work pools in prefect cloud.
