### ISSUE TITLE
Logic to keep ACI deployment name within Azure character limit error

### ISSUE THREAD

**Issue by kbialka-eqr** [PrefectHQ/prefect-azure#146]
# Expectation / Proposal
The logic to assure the ACI deployment name is within Azure's character limit specification applies `len()` to a UUID without first casting to a string. Issue is `workers/container_instance.py` [here](https://github.com/PrefectHQ/prefect-azure/blob/cdd20ef59aba76c1ff2370c1aeb467d574039a63/prefect_azure/workers/container_instance.py#L571).

# Traceback / Example
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/workers/base.py", line 896, in _submit_run_and_capture_errors
    result = await self.run(
  File "/usr/local/lib/python3.10/site-packages/prefect_azure/workers/container_instance.py", line 571, in run
    max_length=55 - len(flow_run.id),
TypeError: object of type 'UUID' has no len()
```

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-azure/#contributing) a pull request to resolve this!

**Comment by zzstoatzz** [comment]
hi @kbialka-eqr - a fix for this has been released `v0.3.7`
