### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by pascal-holy** [PrefectHQ/prefect-azure#63]
I tried to add this package to conda-forge but it doesn't pass the test specifically the build on osx and linux succeeds but not on Windows. 

https://github.com/conda-forge/staged-recipes/pull/21656

The actual error can be seen here https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=636595&view=logs&jobId=240f1fee-52bc-5498-a14a-8361bde76ba0&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=2fb5b0a7-737c-5f5c-8f3f-f6db6174bacf

What am I missing?

**Comment by ahuang11** [comment]
It's likely the star:
`Feel free to ⭐️ or watch [prefect-azure](https://github.com/PrefectHQ/prefect-azure) for updates too!` Let me try updating...

**Comment by pascal-holy** [comment]
Ahh! Thank you for looking into this.
