### ISSUE TITLE
AzureContainerInstanceJob doesn't support Managed Identity to deploy Container Instance for authenticated Image Registry

### ISSUE THREAD

**Issue by montereyharris** [PrefectHQ/prefect-azure#75]
# Expectation / Proposal
AzureContainerInstanceJob only allows the use of username and password for authentication to container registry. Prefect should allow for using Managed Identities to authenticate to Azure Container Registry (ACR). This would allow for agents/flows running on Azure based compute to leverage Azure AD for authentication. This is especially useful in organizations that want to limit access to admin credentials that are used in ACR. 

I propose adding an additional option to block for AzureContainerInstanceJob to allow use of an User Assigned Managed Identity and Azure Container registry exclusively.
Suggestion azure_container_registry which would accept both user name/password or Azure Managed Identity.  
We then update _configure_container_group method to handle both class options with image _registry being default for backwards compatibility

References - 
1. Azure Python SDK ImageRegistryCredential Class- https://learn.microsoft.com/en-us/python/api/azure-mgmt-containerinstance/azure.mgmt.containerinstance.models.imageregistrycredential?view=azure-python
2.  Rest API Reference - https://learn.microsoft.com/en-us/rest/api/container-instances/container-groups/create-or-update?tabs=HTTP#imageregistrycredential
3. ARM Deployment Example - https://learn.microsoft.com/en-us/azure/container-instances/using-azure-container-registry-mi#deploy-using-an-azure-resource-manager-arm-template

# Traceback / Example

- [X] I would like to [help contribute](https://PrefectHQ.github.io/prefect-azure/#contributing) a pull request to resolve this!

**Comment by zzstoatzz** [comment]
Hi @montereyharris - thanks for the issue. This sounds useful.

I noticed you marked yourself as potentially interested in contributing this feature - is there anything I can help clarify about the contribution process?
